# Generated by Django 4.0.4 on 2023-06-18 11:39

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('atdt_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('employee_id', models.CharField(max_length=200)),
                ('location_id', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=400)),
                ('vouchers', models.IntegerField()),
                ('profile', models.ImageField(upload_to=api.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='ClientMaster',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200)),
                ('address', models.CharField(default='c_addr', max_length=400)),
                ('contact_name', models.CharField(default='c_name', max_length=400)),
                ('contact_no', models.CharField(default='c_no', max_length=400)),
                ('active_vouchers', models.IntegerField(default=0)),
                ('used_vouchers', models.IntegerField(default=0)),
                ('last_order_date', models.DateField()),
                ('last_order_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('voucher_id', models.AutoField(primary_key=True, serialize=False)),
                ('validity_date', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
                ('last_used', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='A', max_length=1)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('txn_date', models.DateField()),
                ('txn_id', models.AutoField(primary_key=True, serialize=False)),
                ('txn_amount', models.BigIntegerField()),
                ('initial_amount', models.BigIntegerField()),
                ('redeem_amount', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attendant')),
                ('voucher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.voucher')),
            ],
        ),
    ]
