# Generated by Django 4.0.4 on 2023-06-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
