# Generated by Django 4.0.4 on 2023-06-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_voucher_voucher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='amount',
            new_name='initial_amount',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='validity_date',
        ),
        migrations.AddField(
            model_name='voucher',
            name='last_transaction_id',
            field=models.CharField(default='T', max_length=200),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='last_used',
            field=models.DateTimeField(blank=True),
        ),
    ]
