# Generated by Django 4.0.4 on 2023-06-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_amount_voucher_initial_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmaster',
            name='last_order_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='last_transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
