# Generated by Django 4.0.4 on 2023-06-19 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_agent_id_transactions_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='Voucher_id',
            field=models.ForeignKey(default='B', on_delete=django.db.models.deletion.CASCADE, to='api.voucher'),
            preserve_default=False,
        ),
    ]
