# Generated by Django 4.0.4 on 2023-06-20 16:36

import api.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transactions_voucher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='profile',
            field=models.ImageField(null=True, upload_to=api.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 16, 36, 56, 571192, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='last_used',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 20, 16, 36, 56, 571192, tzinfo=utc), null=True),
        ),
    ]
