# Generated by Django 4.0.4 on 2023-06-22 16:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_attendant_profile_alter_transactions_txn_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='initial_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='left_balance',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='redeem_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 16, 27, 32, 753094, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='last_used',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 22, 16, 27, 32, 752096, tzinfo=utc), null=True),
        ),
    ]
