# Generated by Django 4.0.4 on 2023-06-22 16:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_transactions_initial_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 16, 28, 39, 85619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='last_used',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 22, 16, 28, 39, 85619, tzinfo=utc), null=True),
        ),
    ]
