# Generated by Django 4.0.4 on 2023-06-22 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_transactions_txn_date_alter_voucher_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslogmodel',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 16, 44, 49, 102853, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='last_used',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 22, 16, 44, 49, 102853, tzinfo=utc), null=True),
        ),
    ]
