# Generated by Django 4.0.4 on 2023-06-22 16:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_transactions_txn_date_alter_voucher_last_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 16, 49, 20, 47138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='last_used',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 22, 16, 49, 20, 46137, tzinfo=utc), null=True),
        ),
        migrations.AlterModelTable(
            name='accesslogmodel',
            table=None,
        ),
    ]
