# Generated by Django 4.0.4 on 2023-06-27 13:50

import api.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_transactions_txn_date_alter_voucher_last_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 27, 13, 49, 50, 399351, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='last_used',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 27, 13, 49, 50, 397351, tzinfo=utc), null=True),
        ),
    ]
