# Generated by Django 4.0.4 on 2023-06-29 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_clientmaster_last_order_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('chat_id', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=400)),
                ('employee_id', models.CharField(max_length=200)),
                ('status', models.CharField(default='U', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 9, 13, 35, 778986, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='last_used',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 29, 9, 13, 35, 777926, tzinfo=utc), null=True),
        ),
    ]
