# Generated by Django 4.0.4 on 2023-06-29 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_chat_alter_transactions_txn_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 9, 23, 34, 438164, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 9, 23, 34, 438164, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='last_used',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 29, 9, 23, 34, 438164, tzinfo=utc), null=True),
        ),
    ]
